### ISSUE TITLE
Compilation error because extension requires vsts-task-lib

### ISSUE THREAD

**Issue by Avidres** [bamminger/vsts-queue-build#16]
Hi guys,
I have a compilation error when the queue build is started because vsts library is requerid but I have no idea what I should do to resolve it. Please your help with this problem.
The error is the next:
C:\TFSAgentService\Agent1\tasks\TriggerBuild\2.4.0\index.js:11
const taskLibrary = require("vsts-task-lib/task");
^^^^^
SyntaxError: Use of const in strict mode.
at exports.runInThisContext (vm.js:73:16)
at Module._compile (module.js:443:25)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
 at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:501:10)
at startup (node.js:129:16)
at node.js:814:3

**Comment by bamminger** [comment]
What exactly are you trying to achieve? If you use the published version, there is no compilation or any manual action required.

**Comment by Avidres** [comment]
Hi @bamminger 

I need to compile multiple builds in a new build definition, I also need to compile multiple builds according to tags created and also dependent builds to another builds.

I installed vsts library but the following error occurred:

C:\TFSAgentService\Agent1\tasks\queue-build\1.2.4\task\queue-build.task.js:11
const task_1 = require("vsts-task-lib/task");
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3


I do not know why this error is produce.
I have TFS 2015 update 2

**Comment by bamminger** [comment]
Then this issue is caused by the older TFS version. The extension currently does not support On-Premise TFS due to the fact, that the Microsoft Vsts/TFS Api-Module does it neither.
