### ISSUE TITLE
Always get error "Error: Invalid Resource"

### ISSUE THREAD

**Issue by spashx** [bamminger/vsts-queue-build#33]
Hi,
I'm using TFS 2017 UPD3.1  EN (on premise), build agents are Windows based agent, version 2.122.1
When trying to run 2 build definitions, I always get the following error: "Invalid ressource".
Setting "system.debug=true" does not much help on troubleshooting.

I double checked the documentation, but can't find if I miss something.
Could you please advise where/how to investigate ?
Do you have special requirements regarding node version ?
 Thanks.

2018-09-10T08:28:21.3810282Z ==============================================================================
2018-09-10T08:28:21.3810282Z Task         : Queue Build(s)
2018-09-10T08:28:21.3810282Z Description  : Start new build(s) in your Team Project
2018-09-10T08:28:21.3810282Z Version      : 1.7.0
2018-09-10T08:28:21.3810282Z Author       : jb
2018-09-10T08:28:21.3810282Z Help         : 
2018-09-10T08:28:21.3810282Z ==============================================================================
2018-09-10T08:28:22.1622936Z ##[debug]agent.TempDirectory=D:\agent\agent\_work\_temp
2018-09-10T08:28:22.1622936Z ##[debug]loading inputs and endpoints
2018-09-10T08:28:22.1622936Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2018-09-10T08:28:22.1622936Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2018-09-10T08:28:22.1622936Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2018-09-10T08:28:22.1622936Z ##[debug]loading INPUT_ASYNC
2018-09-10T08:28:22.1622936Z ##[debug]loading INPUT_BUILDCONFIGURATIONTYPE
2018-09-10T08:28:22.1622936Z ##[debug]loading INPUT_BUILDDEFINITIONNAME
2018-09-10T08:28:22.1622936Z ##[debug]loading INPUT_DEBUG
2018-09-10T08:28:22.1622936Z ##[debug]loading INPUT_REQUESTEDFOR
2018-09-10T08:28:22.1622936Z ##[debug]loading INPUT_TEAMPROJECTTYPE
2018-09-10T08:28:22.1622936Z ##[debug]loaded 9
2018-09-10T08:28:22.1622936Z ##[debug]Agent.ProxyUrl=undefined
2018-09-10T08:28:22.1622936Z ##[debug]Agent.CAInfo=undefined
2018-09-10T08:28:22.1622936Z ##[debug]Agent.ClientCert=undefined
2018-09-10T08:28:22.1622936Z ##[debug]Agent.SkipCertValidation=undefined
2018-09-10T08:28:22.1622936Z ##[debug]system.teamFoundationCollectionUri=https://XXXXXXXXXXXXXXXXXXXXXXXXXXXX
2018-09-10T08:28:22.1622936Z ##[debug]Agent.BuildDirectory=D:\agent\agent\_work\22
2018-09-10T08:28:22.1622936Z ##[debug]debug=false
2018-09-10T08:28:22.1622936Z ##[debug]authToken=null
2018-09-10T08:28:22.1622936Z SYSTEMVSSCONNECTION exists true
2018-09-10T08:28:22.1622936Z ##[debug]SYSTEMVSSCONNECTION exists true
2018-09-10T08:28:22.1622936Z ##[debug]requestedFor=true
2018-09-10T08:28:22.1622936Z ##[debug]release.requestedForId=undefined
2018-09-10T08:28:22.1622936Z ##[debug]build.requestedForId=a4232324-c57e-44df-9636-1c961368a954
2018-09-10T08:28:22.1622936Z ##[debug]async=false
2018-09-10T08:28:22.1622936Z ##[debug]buildIdOutputVariable=null
2018-09-10T08:28:22.1622936Z ##[debug]teamProjectType=current
2018-09-10T08:28:22.1622936Z ##[debug]system.teamProject=Administration
2018-09-10T08:28:22.1622936Z ##[debug]Processed: ##vso[task.addattachment type=Distributedtask.Core.Summary;name=Queued Builds;]D:\agent\agent\_work\22\QueueBuild-BuildResult.html
2018-09-10T08:28:22.1622936Z Queued builds linked to build result
2018-09-10T08:28:22.1622936Z ##[debug]task result: Failed
2018-09-10T08:28:22.1778987Z ##[error]Queue build(s) failed
2018-09-10T08:28:22.1778987Z ##[debug]Processed: ##vso[task.issue type=error;]Queue build(s) failed
2018-09-10T08:28:22.1778987Z ##[debug]Processed: ##vso[task.complete result=Failed;]Queue build(s) failed
**2018-09-10T08:28:22.1778987Z Error: Invalid Resource
2018-09-10T08:28:22.1778987Z     at RestClient.<anonymous> (D:\agent\agent\_work\_tasks\queue-build_025bc3d2-c942-42d2-9b76-97db7e884483\1.7.0\node_modules\typed-rest-client\RestClient.js:162:28)**
2018-09-10T08:28:22.1778987Z     at next (native)
2018-09-10T08:28:22.1778987Z     at fulfilled (D:\agent\agent\_work\_tasks\queue-build_025bc3d2-c942-42d2-9b76-97db7e884483\1.7.0\node_modules\typed-rest-client\RestClient.js:6:58)
2018-09-10T08:28:22.1778987Z     at process._tickCallback (internal/process/next_tick.js:109:7)
2018-09-10T08:28:22.1778987Z ##[section]Finishing: Queue build(s) BuildDefABuildDefB

**Comment by bamminger** [comment]
Sorry for the late reply. Has the task ever worked on your TFS installation?

**Comment by spashx** [comment]
Hi,
No, I wanted to validate it against our TFS before deploying it on production instance.

**Comment by bamminger** [comment]
According to the error message and the Microsoft source of the [RestClient](https://github.com/Microsoft/typed-rest-client/blob/master/lib/RestClient.ts#L186), it seems like your server response is inavlid.

Is it possible to try one of the REST Apis from your computer (e.g. with Postman).
Sample Api would be: [Build](https://docs.microsoft.com/en-us/rest/api/vsts/build/builds/get?view=vsts-rest-4.1)

**Comment by spashx** [comment]
>Sample Api would be: : https://docs.microsoft.com/en-us/rest/api/vsts/build/builds/get?view=vsts-rest-4.1

Since we are running TFS 2017 UP3.1, VSTS API 4.1 won't work.
 The latest compatible API is the "previous api" 2.0 (same for TFS 2018).
The closest is: https://docs.microsoft.com/en-us/azure/devops/integrate/previous-apis/build/builds?view=tfs-2017
And this one just works fine.
``
Maybe this is the issue, just to clarify if TFS 2017 is supported or not in your Marketplace page.
(Today only "Team Foundation Server" is specified).

**Comment by bamminger** [comment]
Ok, unfortunately I can't downgrade the vso-node-api too far due to proxy issues that were fixed in the newer versions.
I will check if there is a chance to get it working.

**Comment by bamminger** [comment]
There will be 2 different versions of the task 
v1 will support > 2017 Update 1
v2 VSTS & TFS 2018 Update 2
