### ISSUE TITLE
Connection issues kill task

### ISSUE THREAD

**Issue by bamminger** [bamminger/vsts-queue-build#37]
If the status of a long running build is checked and the request times out due to local build agent issues, the whole build fails.
It would be nice if the task tries again to check for the current build status in case of network issues.

**Comment by bamminger** [comment]
{ Error: connect ETIMEDOUT ...:443
2018-12-19T15:11:58.3689441Z     at Object.exports._errnoException (util.js:1018:11)
2018-12-19T15:11:58.3689441Z     at exports._exceptionWithHostPort (util.js:1041:20)
2018-12-19T15:11:58.3689441Z     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
2018-12-19T15:11:58.3689441Z   code: 'ETIMEDOUT',
2018-12-19T15:11:58.3689441Z   errno: 'ETIMEDOUT',
2018-12-19T15:11:58.3689441Z   syscall: 'connect',
2018-12-19T15:11:58.3689441Z   address: '...',
2018-12-19T15:11:58.3689441Z   port: 443,
2018-12-19T15:11:58.3689441Z   statusCode: undefined }

**Comment by bamminger** [comment]
Retry added to avoid temporarily happening connection issues
