### ISSUE TITLE
Is there an option to turn off storing BuildResult files on disc?

### ISSUE THREAD

**Issue by nc-papo** [bamminger/vsts-queue-build#39]
Hi,
I got this issue with one of my builds that sometimes the build cannot write to the BuildResult.html file and because of this it fails whole Task.
Is there a way to turn off storing/creating BuildResult files on Disc?

Attaching my error log:
```
2020-02-17T20:00:09.1647632Z ##[section]Starting: Queue build: 
2020-02-17T20:00:09.1652744Z ==============================================================================
2020-02-17T20:00:09.1652914Z Task         : Queue Build(s)
2020-02-17T20:00:09.1653034Z Description  : Start new build(s) in your Team Project
2020-02-17T20:00:09.1653145Z Version      : 1.8.0
2020-02-17T20:00:09.1653252Z Author       : jb
2020-02-17T20:00:09.1653391Z Help         :
2020-02-17T20:00:09.1653533Z ==============================================================================
2020-02-17T20:00:09.6846482Z SYSTEMVSSCONNECTION exists true
2020-02-17T20:00:09.9383331Z Build started
2020-02-17T20:00:09.9383773Z       Link: 
2020-02-17T20:00:09.9566124Z { Error: EBUSY: resource busy or locked, unlink 'D:\Builds_2\6\QueueBuild-BuildResult.html'
2020-02-17T20:00:09.9567198Z     at Error (native)
2020-02-17T20:00:09.9567652Z     at Object.fs.unlinkSync (fs.js:1103:18)
2020-02-17T20:00:09.9568049Z     at Function.attach (D:\Builds_2\_tasks\queue-build_025bc3d2-c942-42d2-9b76-97db7e884483\1.8.0\task\util\task-summary.js:13:16)
2020-02-17T20:00:09.9568522Z     at D:\Builds_2\_tasks\queue-build_025bc3d2-c942-42d2-9b76-97db7e884483\1.8.0\task\queue-build.task.js:38:44
2020-02-17T20:00:09.9568923Z     at next (native)
2020-02-17T20:00:09.9569315Z     at fulfilled (D:\Builds_2\_tasks\queue-build_025bc3d2-c942-42d2-9b76-97db7e884483\1.8.0\task\queue-build.task.js:4:58)
2020-02-17T20:00:09.9569712Z     at process._tickCallback (internal/process/next_tick.js:109:7)
2020-02-17T20:00:09.9569979Z   errno: -4082,
2020-02-17T20:00:09.9570202Z   code: 'EBUSY',
2020-02-17T20:00:09.9570434Z   syscall: 'unlink',
2020-02-17T20:00:09.9570728Z   path: 'D:\\Builds_2\\6\\QueueBuild-BuildResult.html' }
2020-02-17T20:00:09.9581760Z Queued builds linked to build result
2020-02-17T20:00:09.9626689Z ##[error]Queue build(s) failed
2020-02-17T20:00:09.9738990Z ##[section]Finishing: Queue build: 
```

**Comment by bamminger** [comment]
New option available in Task v2 
![image](https://user-images.githubusercontent.com/22851567/78451174-24009500-7684-11ea-859b-5bacfcc3825c.png)
